spring:
  application:
    name: client-service
  cloud:
    config:
      uri: http://localhost:8888
  profiles: zone1
  rabbitmq:
    host: 192.168.1.107
    port: 5672
    username: guest
    password: guest
eureka:
  instance:
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
server:
  port: ${PORT:8087}

foo: foo version 9